QuanfitaSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView, page_not_found, live2d
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', IndexView.as_view(), name="index"),
    path(r'', include('Blog.urls',namespace='Blog')),
    path(r'', include('api.urls',namespace='Api')),
    path(r'', include('Video.urls',namespace='Video')),
    path(r'', include('User.urls',namespace='User')),
    url(r'^captcha', include('captcha.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'live2d/',live2d),
    #path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
hander404 = page_not_found

api/urls.py
from django.urls import path
from rest_framework import routers
from .views import BlogViewSet, BlogDetail

app_name = 'Api'

urlpatterns = [
    path('api/', BlogViewSet.as_view()),
    path('api/<int:pk>/', BlogDetail.as_view())
]

apps/Blog/urls.py
from .views import BlogView, BlogListView
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Blog'

urlpatterns = [
    path(r'blog-list/', BlogListView.as_view(), name="blog-list"),
    path(r'blog/', BlogView.as_view(), name="blog"),
]

apps/Video/urls.py
from django.urls import path, include
from .views import VideoView, VideoListView

app_name = 'Video'

urlpatterns = [
    path(r'video-list/',VideoListView.as_view(),name='video-list'),
    path(r'video/',VideoView.as_view(),name='video'),
]

apps/Blog/models.py
from django.utils import timezone as datetime
from django.db import models

class Category(models.Model):
    """分类"""
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Tag(models.Model):
    """标签"""
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Blog(models.Model):
    """文章"""
    title = models.CharField(max_length=100)
    body = models.TextField()
    author = models.CharField(max_length=20)
    created_time = models.DateTimeField(datetime.now)
    excerpt = models.CharField(max_length=200, blank=True)  # 文章摘要，可为空
    category = models.ForeignKey(Category, on_delete=True)  # ForeignKey表示1对多（多个post对应1个category）
    tags = models.ManyToManyField(Tag, blank=True)
    views = models.PositiveIntegerField(default=0)  # 阅读量

    def __str__(self):
        return "<Blog: %s>" % self.title

apps/Photo/models.py
from django.utils import timezone as datetime
from django.db import models

def upload_to(instance, filename):
    return '/'.join(['image', instance.name, filename])

# Create your models here.
class Photo(models.Model):
    name = models.CharField(max_length=50, verbose_name=u"图册名称")
    tags = models.CharField(max_length=10, verbose_name=u"标签")
    # love_nums = models.IntegerField(default=0, verbose_name=u"点赞数")
    # fav_nums = models.IntegerField(default=0, verbose_name=u"收藏数")
    # download_nums = models.IntegerField(default=0, verbose_name=u"下载数")
    image = models.ImageField(upload_to=upload_to, verbose_name=u"照片", max_length=100)
    desc = models.CharField(max_length=1000, verbose_name=u"说明")
    add_time = models.DateTimeField(default=datetime.now)

    class Meta:
        verbose_name = u"图册"
        verbose_name_plural = verbose_name

    def __str__(self):
        return "<Photo: %s>" % self.name

    def image_data(self):
        return format_html(
            '<img src="{}" width="100px"/>',
            self.image.url,
        )

apps/Video/models.py
from django.utils import timezone as datetime
from django.db import models
import json
import requests

# https://www.bilibili.com/video/av68090180/
# <iframe src="//player.bilibili.com/player.html?aid=68090180&cid=118018632&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"> </iframe>
# http://api.bilibili.com/view?type=jsonp&appkey=8e9fc618fbd41e28&id=68186226&page=1&callback=jQuery17202164493076486218_1568945060574&_=1568945060791
# Create your models here.
class Video(models.Model):
    aid = models.CharField(max_length=20, verbose_name=u"aid")
    name = models.CharField(max_length=50, verbose_name=u"视频名称")
    tags = models.CharField(max_length=10, verbose_name=u"标签")
    url = models.CharField(max_length=100, verbose_name=u"链接")
    # love_nums = models.IntegerField(default=0, verbose_name=u"点赞数")
    # fav_nums = models.IntegerField(default=0, verbose_name=u"收藏数")
    # download_nums = models.IntegerField(default=0, verbose_name=u"下载数")
    cover = models.CharField(max_length=100, verbose_name=u"封面")
    desc = models.CharField(max_length=1000, verbose_name=u"说明")
    add_time = models.DateTimeField(default=datetime.now)

    class Meta:
        verbose_name = u"视频"
        verbose_name_plural = verbose_name

    def __str__(self):
        return "<Video: %s>" % self.name

    def getdata(self,aid):
        self.aid = aid
        api_url = 'http://api.bilibili.com/view?type=json&appkey=8e9fc618fbd41e28&id=%s&page=1&callback=jQuery17202164493076486218_1568945060574&_=1568945060791' % self.aid
        self.content = json.loads(requests.get(api_url).text)
        self.name = content['title']
        self.tags = content['tag']
        self.url = "http://player.bilibili.com/player.html?aid=%s&cid=118018632&page=1" % self.aid
        self.cover = content['pic']
        self.desc = content['description']
        self.add_time = content['created_at']

apps/Blog/views.py
from django.shortcuts import render, redirect
from django.template.loader import get_template
from django.http import HttpResponse
from django.core.paginator import Paginator
from .models import Blog,Category,Tag
from User.models import UserProfile as User
from django.views import View
import markdown
import os

# Create your views here.

class BlogView(View):
    def get(self,request):
        """
        博客页面
        :param request
        :return:
        """
        session = request.session
        try:
            user = User.objects.get(id=session['user_id'])
        except:
            print('User is not login!')
        blog = request.GET.get('id')
        blog = Blog.objects.get(id=blog)
        if blog is None:
            return
        name = blog.title #''Windows10+Anaconda+TensorFlow(CPU & GPU)环境快速搭建''#Blog.title
        template = get_template('blog-single.html')
        print(os.path.dirname(__file__))
        html = template.render({
            'session': request.session,
            'user': user,
            'tag':'Blog',
            'blog_category': blog.category,
            'category': Category.objects.all(),
            'title': name.replace('_',' '),
            'author': blog.author,
            'date': blog.created_time,
            'content': blog.body
        })
        return HttpResponse(html)#render(request,template_name='Blog.html',context=html)

class BlogListView(View):
    """docstring for BlogListView"""
    def get(self, request):
        session = request.session
        try:
            user = User.objects.get(id=session['user_id'])
        except:
            print('User is not login!')
        blogs = Blog.objects.all()

        limit = 5
        paginator = Paginator(blogs, limit)

        page = request.GET.get('page', 1)
        bloglist = paginator.page(page)

        template = get_template('blogs.html')
        html = template.render({
            'session': request.session,
            'user': user,
            'tag':'Blog',
            'category': Category.objects.all(),
            'content': bloglist
        })
        return HttpResponse(html)

apps/Video/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.template.loader import get_template
from .models import Video
from User.models import UserProfile as User
from django.views import View

# Create your views here.
class VideoView(View):
    """docstring for VideoView"""
    def get(self,request):
        session = request.session
        try:
            user = User.objects.get(id=session['user_id'])
        except:
            print('User is not login!')
        video = request.GET.get('id')
        video = Video.objects.get(id=video)

        content = {
                'session': session,
                'user': user,
                'tag': 'Video',
                'category': 'Video',
                'title': video.name,
                'author': 'Quanfita',
                'video_url': video.url,
                'description': video.desc,
                'date': video.add_time
        }

        temp = get_template('video-single.html')
        html = temp.render(content)
        return HttpResponse(html)

class VideoListView(View):
    """docstring for VideoListView"""
    def get(self, request):
        session = request.session
        try:
            user = User.objects.get(id=session['user_id'])
        except:
            print('User is not login!')
        videos = Video.objects.all()

        limit = 5
        paginator = Paginator(videos, limit)

        page = request.GET.get('page', 1)
        videolist = paginator.page(page)

        template = get_template('videos.html')
        html = template.render({
            'session': session,
            'user': user,
            'tag':'Video',
            'content': videolist
        })
        return HttpResponse(html)
        

templates/blog-single.html
{% extends "single.html" %}
{% load static %}
                    {% block contentbody %}
                <div class="blog-single">
                    <!--<h1>Recent Blog Posts</h1>-->
                    <div class="post_item">
                        <!--<img src="{% static 'images/blog1.jpg' %}" alt="blog">-->
                        
                        <h2><a href="#">{{ title }}</a></h2>
                        <ul class="post-tools">
                            <li class="admin"><a href="#" >{{ tag }}</a></li><!--class="category-ttl"-->
                            <li class="admin"><a href="#">{{ author }}</a></li>
                            <li class="date">{{ date }}</li>
                        </ul>
                        <script type="text/javascript" async
                          src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?...">
                        </script>
                        <div class="post-text">
                        {{ content | safe }}
                        </div>
                        <div class="shared-sec right">
                            <ul>
                                <li> Share On :</li>
                                <li>
                                    <a href="#"><span class="fab fa-facebook"></span></a>
                                </li>
                                <li>
                                    <a href="#"><span class="fab fa-weibo" color='#C43C3C'></span></a>
                                </li>
                                <li>
                                    <a href="https://twitter.com/Quanfita"><span class="fab fa-twitter"></span></a>
                                </li>
                                <li>
                                    <a href="#"><span class="fab fa-weixin" color='green'></span></a>
                                </li>
                                <li>
                                    <a href="https://space.bilibili.com/134755800"><span class="fab fa-bilibili" color='pink'></span></a>
                                </li>
                                <li>
                                    <a href="https://github.com/Quanfita"><span class="fa fa-link"></span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                    {% endblock %}

templates/blogs.html
{% extends "single.html" %}
{% load static %}
                {% block contentbody %}
                <h1>Recent Blogs</h1>
                {% for item in content %}
                <div class="post_item">
                    <!--<img src="{% static 'images/blog1.jpg' %}" alt="blog">-->
                    <a href="/category" class="category-ttl">{{ item.category }}</a>
                    <div class="shared-sec right">
                        <ul>
                            <li> Share On :</li>
                            <li>
                                <a href="#"><span class="fab fa-facebook"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-instagram"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-twitter"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-pinterest"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-google-plus-g"></span></a>
                            </li>
                        </ul>
                    </div>
                    <h2><a href="{% url 'Blog:blog' %}?id={{ item.id }}">{{item.title}}</a></h2>
                    <ul class="post-tools">
                        <li class="admin"><a href="#">{{ item.author }} </a></li>
                        <li class="date">{{ item.created_time }}</li>
                    </ul>
                    <h6>{{ item.excerpt }}</h6>
                    <a href="{% url 'Blog:blog' %}?id={{ item.id }}" class="readmore-btn">Continue...</a>
                </div>
                {% endfor %}
                <!--
                <div class="post_item">
                    <img src="images/blog1.jpg" alt="blog">
                    <a href="#" class="category-ttl">Health</a>
                    <div class="shared-sec right">
                        <ul>
                            <li> Share On :</li>
                            <li>
                                <a href="#"><span class="fab fa-facebook"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-instagram"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-twitter"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-pinterest"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-google-plus-g"></span></a>
                            </li>
                        </ul>
                    </div>
                    <h2><a href="#">Girl walking on the road in early morning for mood.</a></h2>
                    <ul class="post-tools">
                        <li class="admin"><a href="#">Admin </a></li>
                        <li class="date">23 Jan 2018</li>
                    </ul>
                    <h6>Lorem Ipsum is simply dummy text of the printing and typetook a galley of type and scrambled it to make a type <a href="#">specimen book</a>. It has survived not only fiveLorem Ipsum is simply dummy text of the printing and typetook a galley of type and scrambled it to make a type specimen book. It has survived not only </h6>
                    <a href="" class="readmore-btn">Continue...</a>
                </div>
                <div class="post_item">
                    <img src="images/blog1.jpg" alt="blog">
                    <a href="#" class="category-ttl">Health</a>
                    <div class="shared-sec right">
                        <ul>
                            <li> Share On :</li>
                            <li>
                                <a href="#"><span class="fab fa-facebook"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-instagram"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-twitter"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-pinterest"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-google-plus-g"></span></a>
                            </li>
                        </ul>
                    </div>
                    <h2><a href="#">Girl walking on the road in early morning for mood.</a></h2>
                    <ul class="post-tools">
                        <li class="admin"><a href="#">Admin </a></li>
                        <li class="date">23 Jan 2018</li>
                    </ul>
                    <h6>Lorem Ipsum is simply dummy text of the printing and typetook a galley of type and scrambled it to make a type <a href="#">specimen book</a>. It has survived not only fiveLorem Ipsum is simply dummy text of the printing and typetook a galley of type and scrambled it to make a type specimen book. It has survived not only </h6>
                    <a href="" class="readmore-btn">Continue...</a>
                </div>
                <div class="post_item">
                    <img src="images/blog1.jpg" alt="blog">
                    <a href="#" class="category-ttl">Health</a>
                    <div class="shared-sec right">
                        <ul>
                            <li> Share On :</li>
                            <li>
                                <a href="#"><span class="fab fa-facebook"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-instagram"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-twitter"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-pinterest"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-google-plus-g"></span></a>
                            </li>
                        </ul>
                    </div>
                      <h2><a href="#">Girl walking on the road in early morning for mood.</a></h2>
                    <ul class="post-tools">
                        <li class="admin"><a href="#">Admin </a></li>
                        <li class="date">23 Jan 2018</li>
                    </ul>
                    <h6>Lorem Ipsum is simply dummy text of the printing and typetook a galley of type and scrambled it to make a type <a href="#">specimen book</a>. It has survived not only fiveLorem Ipsum is simply dummy text of the printing and typetook a galley of type and scrambled it to make a type specimen book. It has survived not only </h6>
                    <a href="" class="readmore-btn">Continue...</a>
                </div>
                <div class="post_item">
                    <img src="images/blog1.jpg" alt="blog">
                    <a href="#" class="category-ttl">Health</a>
                    <div class="shared-sec right">
                        <ul>
                            <li> Share On :</li>
                            <li>
                                <a href="#"><span class="fab fa-facebook"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-instagram"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-twitter"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-pinterest"></span></a>
                            </li>
                            <li>
                                <a href="#"><span class="fab fa-google-plus-g"></span></a>
                            </li>
                        </ul>
                    </div>
                      <h2><a href="#">Girl walking on the road in early morning for mood.</a></h2>
                    <ul class="post-tools">
                        <li class="admin"><a href="#">Admin </a></li>
                        <li class="date">23 Jan 2018</li>
                    </ul>
                    <h6>Lorem Ipsum is simply dummy text of the printing and typetook a galley of type and scrambled it to make a type <a href="#">specimen book</a>. It has survived not only fiveLorem Ipsum is simply dummy text of the printing and typetook a galley of type and scrambled it to make a type specimen book. It has survived not only </h6>
                    <a href="" class="readmore-btn">Continue...</a>
                </div>-->
                <button class="load-more-btn">load more</button>
            </div>
            {% endblock %}
{% block realtedblock %}
{% endblock %}

templates/personal.html
{% extends "base.html" %}
{% load static %}
<!-- 介绍条 -->
{% block mainbody %}
<!--
    <section class="container-fluid introduce">
    	<div class="row">
    		<div class="col-md-12"> 
    				<h1>个人中心<em>&nbsp;&nbsp;&nbsp;personal center</em></h1>
    		</div>
    	</div>
    </section>-->

    <!-- 左右分栏内容 -->
    <script type="text/javascript">
        function checkUser(){
        var result = document.getElementById("email").value;
        var password = document.getElementById("password").value;

        if(result == ""  ){
            alert("用户名不能为空");
            return false;
        }
        if(password == ""  ){
            alert("密码不能为空");
            return false;
        }
            document.getElementById("login-form").submit();
        }
    </script>
    
    <section class="trending-tabsec">
        <div class="container">
            <ul class="nav nav-tabs" role="tablist" style="float: left;">

                <li class="nav-item" style="width: 150px;text-align: center;">
                    <a class="nav-link active" href="#info" role="tab" data-toggle="tab">我的信息</a>
                </li>
                <li class="nav-item" style="width: 150px;text-align: center;">
                    <a class="nav-link" href="#blog" role="tab" data-toggle="tab">我的博客</a>
                </li>
                <li class="nav-item" style="width: 150px;text-align: center;">
                    <a class="nav-link" href="#video" role="tab" data-toggle="tab">我的视频</a>
                </li>
                <li class="nav-item" style="width: 150px;text-align: center;">
                    <a class="nav-link" href="#setting" role="tab" data-toggle="tab">设置</a>
                </li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content" style="border-bottom: 1px solid #ccc;margin-top: 0px;padding-top: 0px;">
            <div role="tabpanel" class="tab-pane fade active" id="info">
                <div class="row" style="margin-left: 20px;margin-right: 20px;border-bottom: 1px solid #ccc;">
                    <div class="col-md-4" style="padding: 10px">
                    <span class="fa fa-vcard" aria-hidden="true"></span>我的信息
                    </div>
                </div>
                <form enctype="multipart/form-data" method="post" id="info-form">
                <div class="row">
                    <div class="col-md-4">
                        <ul style="margin-right: 10px;margin-left: 40px;margin-bottom: 80px;">
                            <li style="padding: 10px">
                                    <div class="list-group">
                                        <div style="font-size: 20px;font-family: 'Microsoft YaHei';padding-bottom: 10px;">
                                        {{ info_form.avatar.label }}</div>
                                        <center><a href="#"><img class="img-circle" src="/{{ user.avatar }}"
                                             style="width: 80px;height: 80px;"/></a></center>
                                        <!--
                                        <input type="file" name="image" accept="image/*" id="id_image"></p>-->
                                    </div>
                            </li>
                            <li style="padding: 10px">
                                <div class="list-group">
                                    <div style="font-size: 20px;font-family: 'Microsoft YaHei';padding-bottom: 10px;">
                                    {{ info_form.nick_name.label }}</div>
                                    {{ info_form.nick_name }}
                                </div>
                            </li>
                            <li style="padding: 10px">
                                <div class="list-group">
                                    <div style="font-size: 20px;font-family: 'Microsoft YaHei';padding-bottom: 10px;">
                                    {{ info_form.sex.label }}</div>
                                    {{ info_form.sex }}
                                </div>
                            </li>
                            <li style="padding: 10px">
                                <div class="list-group">
                                    <div style="font-size: 20px;font-family: 'Microsoft YaHei';padding-bottom: 10px;">
                                    {{ info_form.email.label }}</div>
                                    {{ info_form.email }}
                                </div>
                            </li>
                            <li style="padding: 10px">
                                <div class="list-group">
                                    <div style="font-size: 20px;font-family: 'Microsoft YaHei';padding-bottom: 10px;">
                                    {{ info_form.mobile.label }}</div>
                                    {{ info_form.mobile }}
                                </div>
                            </li>
                            
                        </ul>
                    </div>
                    <div class="col-md-8">
                        <ul style="margin-left: 10px;margin-right: 40px;margin-bottom: 80px; ">
                            <li style="padding: 10px">
                                <div class="list-group">
                                    <div style="font-size: 20px;font-family: 'Microsoft YaHei';padding-bottom: 10px;">
                                    {{ info_form.birthday.label }}</div>
                                    <div style="width: 200px">{{ info_form.birthday }}</div>
                                </div>
                            </li>
                            <li style="padding: 10px;">
                                <div class="list-group">
                                    <div style="font-size: 20px;font-family: 'Microsoft YaHei';padding-bottom: 10px;">
                                    {{ info_form.signature.label }}</div>
                                    {{ info_form.signature }}
                                </div>
                            </li>

                            <li>
                                <div class="col-md-8" style="padding-top: 10px">
                                    <center><button type="submit" class="category-ttl" style="background-color: #002157;width: 120px;font-size: 18px; font-family: 'Microsoft YaHei'" onclick="checkUser()">保存</button></center>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </form>
            </div>
        </div>
                 <!--
                 <div class="row small-post">
                     <div class="col-md-4 col-sm-8">
                         <div class="post-content">
                             <figure style="background:url({% static './images/tab4.jpg'%})no-repeat"></figure>
                             <div class="content">
                                 <a href="#">
                                     <h3 class="post-ttl">Girl walking on the road in early morning for mood.</h3>
                                 </a>
                                 <ul class="post-tools">
                                     <li class="admin"><a href="#">Admin </a></li>
                                     <li class="date">23 Jan 2018</li>
                                 </ul>
                             </div>
                         </div>
                     </div>
                     <div class="col-md-4 col-sm-8">
                         <div class="post-content">
                             <figure style="background:url({% static './images/tab5.jpg' %})no-repeat"></figure>
                             <div class="content">
                                 <a href="#">
                                     <h3 class="post-ttl">Girl walking on the road in early morning for mood.</h3>
                                 </a>
                                 <ul class="post-tools">
                                     <li class="admin"><a href="#">Admin </a></li>
                                     <li class="date">23 Jan 2018</li>
                                 </ul>
                             </div>
                         </div>
                     </div>
                     <div class="col-md-4 col-sm-8">
                         <div class="post-content">
                             <figure style="background:url({% static './images/tab6.jpg' %})no-repeat"></figure>
                             <div class="content">
                                 <a href="#">
                                     <a href="#">
                                         <h3 class="post-ttl">Girl walking on the road in early morning for mood.</h3>
                                     </a>
                                 </a>
                                 <ul class="post-tools">
                                     <li class="admin"><a href="#">Admin </a></li>
                                     <li class="date">23 Jan 2018</li>
                                 </ul>
                             </div>
                         </div>
                     </div>
                 </div>-->
          </div>
    </section>
    {% endblock %}